### ISSUE TITLE
URLS not being stripped properly in ocn_link_expander.py

### ISSUE THREAD

**Issue by Plastix** [bcbwilla/nimbus#25]
``` python
Traceback (most recent call last):
  File "nimbus.py", line 172, in <module>
    Nimbus(config_filename).run()
  File "nimbus.py", line 106, in run
    self.process_event(event)
  File "nimbus.py", line 87, in process_event
    plugin.on_event(self, dict(event), response)
  File "nimbus/plugins/ocn_link_expander.py", line 153, in on_event
    for a in le.process_urls():
  File "nimbus/plugins/ocn_link_expander.py", line 31, in process_urls
    yield ForumScraper(url).get_data()
  File "nimbus/plugins/ocn_link_expander.py", line 60, in get_data
    soup = self.make_soup()
  File "nimbus/plugins/ocn_link_expander.py", line 45, in make_soup
    r = requests.get(self.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 567, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 641, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '(<https://oc.tc/forums/topics/55b1d58e5f35b94af3007c75>)'
```

**Comment by Plastix** [comment]
This has to do with how ocn_link_expander finds links. Typing something like `(oc.tc/forums/hi)` in a message causes a `InvalidSchema` exception from `requests` because it tries to request the URL `(<http://oc.tc/forums/hi|oc.tc/forums/hi>)`

I'll write a more robust way of finding urls similar to what is in utils for stripping URLs.
