### ISSUE TITLE
ocn_link_expander.py: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Brottweiler** [bcbwilla/nimbus#37]
``` python
02/21/2016 05:54:30 AM __main__ ERROR object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/brott/myEnv/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/brott/nimbus_community/plugins/ocn_link_expander.py", line 155, in on_event
    for a in le.process_urls():
  File "/home/brott/nimbus_community/plugins/ocn_link_expander.py", line 31, in process_urls
    yield ForumScraper(url).get_data()
  File "/home/brott/nimbus_community/plugins/ocn_link_expander.py", line 82, in get_data
    d['text'] = self.decratain(text)
  File "/home/brott/nimbus_community/plugins/ocn_link_expander.py", line 95, in decratain
    if len(text) >= limit:
TypeError: object of type 'NoneType' has no len()
```

**Comment by Plastix** [comment]
Duplicate issue. See #13. This is a bug because of hidden posts / pagination on the forums.
